
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "http://192.168.7.121:4000"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: /blogs

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: false

#############
# HTML Head #
#############

lang: "en"
author: "Hang (Harry) Blogs"
title: "We don't get older, we get better!"
description: "Blog and website of Harry. Just share to be shared!"
keywords: "sysadmin, networking, amazon web service"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/background.png"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "The lower you fall, the higher you'll fly."
  - text: "If you fail to plan, you are planning to fail"

me-img: "/img/meinthree.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "hangnt1001"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/meintwo.png"
    date: "September 2013 - Today"
    description: "Saving the world!"
  - image: "/img/meinone.png"
    date: "August 2009 - September 2013"
    description: "Being a student at UIT"

# First image of the Timeline

timeline-img: "/img/meinfour.png"

###########
# Contact #
###########

email: "golden.eyes.1412@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Harry Nguyen is an awesome person. Abosolutely true!."
author_blurb_image: "/img/meinthree.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/golden.eyes3"
  - title: "linkedin"
    url: "https://vn.linkedin.com/in/hang-harry-nguyen-74585278"
#  - title: "github"
#    url: "https://github.com/PanosSakkos/personal-jekyll-theme"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

#keybase-username: hangnt
#keybase-in-social: True
#keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
